### ISSUE TITLE
1.20.1 support when?

### ISSUE THREAD

**Issue by ghost** [slicedlime/seasons#24]

**Comment by slicedlime** [comment]
Likely never. I've started upgrading the pack to 1.20.2.

**Comment by Cosmeak** [comment]
Do we have an update on this ?

**Comment by BUTTER-BEAR** [comment]
> Do we have an update on this ?
@Cosmeak 
I have a un-official update to 1.21.1 i *just* did for someone(since im in a datapack server and wanted to give it a try), i do not know datapacks well as ive just started a few days ago, but ive did a bit of testing and all *seems* to work. if you want to give it a test i can send you the datapack zip. Also if SlicedLime wants the file removed i can do so, just thought i would update it since someone asked and i saw this hasnt been touched in awhile. Plus they are of course allowed to do whatever with the upload.

**Comment by OpMstrR** [comment]
@BUTTER-BEAR 
> > I have a un-official update to 1.21.1 

Can you send it to me, please?

**Comment by BUTTER-BEAR** [comment]
@OpMstrR
Sure, here you go! Note, i can not say for certain if this is properly done as i am very new to datapacks, i just know that it seems to work.
[seasons-Unoffical-Port.zip](https://github.com/user-attachments/files/18004105/seasons-Unoffical-Port.zip)

**Comment by OpMstrR** [comment]
@BUTTER-BEAR  thank you very much!

**Comment by BUTTER-BEAR** [comment]
@OpMstrR no problem! Let me know how it goes!

**Comment by slicedlime** [comment]
1.21.4 is now supported. Older version support is not planned.
